server:
  port: 80
spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    username: root
#    password: 112367
#    url: jdbc:mysql://39.106.120.220:3306/yizhong?useUnicode=true&characterEncoding=UTF-8


  datasource:
    url: jdbc:mysql://39.106.120.220:3306/yizhong?useSSL=false&characterEncoding=utf-8
    username: root
    password: 112367
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 10
    minIdle: 5
    maxActive: 15
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j2
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000

    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss

    thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML5
      servlet:
        content-type: text/html
    druid:
      username: root
      password: 112367
      url: jdbc:mysql://39.106.120.220:3306/yizhong?u seUnicode=true&characterEncoding=UTF-8
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 5
      min-idle: 5
      max-active: 10
      pool-prepared-statements: true

mybatis:
  mapper-locations: classpath*:/mappers/*.xml
  type-aliases-package: org.llaccj.yizhong.module
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error